### ISSUE TITLE
config list是双系统？

### ISSUE THREAD

**Issue by johnyang007** [abnerxc/efi#1]
我看config list里有Microsoft 选项。这个efi是双系统吗？
还有这个efi现在有什么问题没解决吗？

**Comment by Tlz-1994** [comment]
我下载的也是有一个声卡网卡万能驱动的 config，但是用这个 config 的话会不能启动

**Comment by abnerxc** [comment]
@johnyang007 @Tlz-1994 不是双系统，我这边使用没有任何问题。全部完美

**Comment by Tlz-1994** [comment]
> @johnyang007 @Tlz-1994 不是双系统，我这边使用没有任何问题。全部完美

嗯，我这边也安装成功了，有个疑问，你们有没有遇到休眠后突然自动打开的问题。

**Comment by johnyang007** [comment]
显存怎么设置64m，我怎么都找不到地方。好像是跟着uefi和csm走。csm是64m，uefi是32m

**Comment by johnyang007** [comment]
CFG lock 这个也找不到地方关闭。默认是关闭的吗

**Comment by Tlz-1994** [comment]
默认不是关闭的，你直接在 bios 里面搜索关键字就行了，不懂就 google




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ken"<notifications@github.com&gt;; 
发送时间: 2020年7月9日(星期四) 晚上10:43
收件人: "abner-xu/efi"<efi@noreply.github.com&gt;; 
抄送: "猫城九事"<156419435@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [abner-xu/efi] config list是双系统？ (#1)





 
CFG lock 这个也找不到地方关闭。默认是关闭的吗

**Comment by johnyang007** [comment]
嗯，微星的配置是挺深的。最后安装好了。就是有个问题不知道是不是我硬件的问题导致的。每天几乎必定会突然自动重启一次，老哥有没有遇到过这个情况？

**Comment by abnerxc** [comment]
> 嗯，微星的配置是挺深的。最后安装好了。就是有个问题不知道是不是我硬件的问题导致的。每天几乎必定会突然自动重启一次，老哥有没有遇到过这个情况？

没有哦，我使用起来还挺稳定的。没遇到什么坑

**Comment by johnyang007** [comment]
我再找找问题，可能是硬件问题。
