### ISSUE TITLE
卡在了白苹果

### ISSUE THREAD

**Issue by vito7zhang** [abnerxc/efi#3]
install macOS catalina的时候，卡在了白苹果，进度条也没有。。。

**Comment by William-HL1991** [comment]
> install macOS catalina的时候，卡在了白苹果，进度条也没有。。。

从480换到5500xt，同样卡在这里，懒得找0.6.0，不知道你解决了么？我可能是因为我之前用的非5000系显卡，没有改boot-args导致的

**Comment by vito7zhang** [comment]
> > install macOS catalina的时候，卡在了白苹果，进度条也没有。。。
> 
> 从480换到5500xt，同样卡在这里，懒得找0.6.0，不知道你解决了么？我可能是因为我之前用的非5000系显卡，没有改boot-args导致的

我的已经找到原因，我是主板的CFG Lock没解锁导致的

**Comment by William-HL1991** [comment]
> > > install macOS catalina的时候，卡在了白苹果，进度条也没有。。。
> > 
> > 
> > 从480换到5500xt，同样卡在这里，懒得找0.6.0，不知道你解决了么？我可能是因为我之前用的非5000系显卡，没有改boot-args导致的
> 
> 我的已经找到原因，我是主板的CFG Lock没解锁导致的

我回去再看看，我记得 bios 我都设置好了~

**Comment by William-HL1991** [comment]
> > > install macOS catalina的时候，卡在了白苹果，进度条也没有。。。
> > 
> > 
> > 从480换到5500xt，同样卡在这里，懒得找0.6.0，不知道你解决了么？我可能是因为我之前用的非5000系显卡，没有改boot-args导致的
> 
> 我的已经找到原因，我是主板的CFG Lock没解锁导致的

感谢提醒，真的是拔掉显卡bios还原了~
